apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- role_binding.yaml
- role.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- aggregated_role.yaml
- auth_proxy_service.yaml
- auth_proxy_role.yaml
- auth_proxy_role_binding.yaml
