name: Release test

# Note: This workflow does not build for releases. It attempts to build release binaries daily to ensure the repo
# is in a good state.

on:
  schedule:
    # Cron for every Thursday at 12:00 UTC.
    - cron: "0 12 * * 4"

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  daily-release-build:
    name: Broken Links
    strategy:
      fail-fast: false
      matrix:
        branch: [ main, release-1.3, release-1.2 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # tag=v3.3.0
        with:
          ref: ${{ matrix.branch }}
      - name: Set env
        run: echo "RELEASE_TAG=v0.0-fake" >> $GITHUB_ENV
      - name: build release binaries
        run: |
          make release