on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]
    # Don't run this check on PRs created by the cherry-pick bot,
    # as the PR description is too short, but otherwise the PRs are fine.
    branches-ignore:
      - k8s-infra-cherrypick-robot/**

jobs:
  verify:
    runs-on: ubuntu-latest
    name: verify PR contents
    steps:
    - name: Verifier action
      id: verifier
      uses: kubernetes-sigs/kubebuilder-release-tools@v0.2.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
