name: Weekly check all Markdown links

on:
  schedule:
    # Cron for every Monday at 12:00 UTC.
    - cron: "0 12 * * 1"

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  markdown-link-check:
    name: Broken Links
    strategy:
      fail-fast: false
      matrix:
        branch: [ main, release-1.8, release-1.7 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # tag=v4.2.0
        with:
          ref: ${{ matrix.branch }}
      - uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # tag=v1
        with:
          use-quiet-mode: 'yes'
          config-file: .markdownlinkcheck.json
