name: Weekly release test

# Note: This workflow does not build for releases. It attempts to build release binaries periodically to ensure the repo
# release machinery is in a good state.

on:
  schedule:
    # Cron for every day at 12:00 UTC.
    - cron: "0 12 * * *"

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  weekly-test-release:
    name: Test release
    strategy:
      fail-fast: false
      matrix:
        branch: [ main, release-1.7, release-1.6 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # tag=v4.1.2
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0
      - name: Set env
        run:  echo "RELEASE_TAG=v9.9.9-fake" >> $GITHUB_ENV
      - name: Set fake tag for release
        run: |
          git tag ${{ env.RELEASE_TAG }}
      - name: Calculate go version
        run: echo "go_version=$(make go-version)" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # tag=v5.0.0
        with:
          go-version: ${{ env.go_version }}
      - name: Test release
        run: |
          make release